language: php

sudo: false
dist: trusty

php:
  - 7.2

before_install:
  - cp .env.travis .env
  - touch database/database.sqlite
  - travis_retry composer self-update --preview

install:
  - travis_retry composer install --no-interaction --prefer-dist

before_script:
  - php artisan key:generate
  - php artisan migrate

script:
  - php vendor/bin/phpunit --coverage-text
